/**
 * Share route layout — Server Component.
 *
 * This thin server wrapper allows us to export Next.js `metadata` and
 * inject JSON-LD structured data for the /share page, even though the
 * page itself is a "use client" component (client components cannot
 * export `metadata` directly).
 */
import type { Metadata } from "next";
import { JsonLd } from "@/app/components/JsonLd";

export const metadata: Metadata = {
  title: "My Stellar Wrap",
  description:
    "Check out my Stellar blockchain year in review — transactions, DeFi persona, and vibes! Generated by Stellar Wrap.",
  openGraph: {
    title: "My Stellar Wrap",
    description:
      "Check out my Stellar blockchain year in review — transactions, DeFi persona, and vibes!",
    type: "article",
    url: "/share",
    images: [
      {
        url: "/api/og",
        width: 1200,
        height: 1200,
        alt: "Stellar Wrap share card",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "My Stellar Wrap",
    description:
      "Check out my Stellar blockchain year in review — transactions, DeFi persona, and vibes!",
    images: ["/api/og"],
  },
};

/**
 * CreativeWork JSON-LD for the share page.
 *
 * The /share page represents a user's personalised wrap — a creative
 * data-driven summary of their on-chain year, making CreativeWork the
 * most appropriate schema.org type.
 */
const sharePageJsonLd = {
  "@context": "https://schema.org",
  "@type": "CreativeWork",
  name: "Stellar Wrap — On-Chain Year in Review",
  description:
    "A personalised summary of Stellar blockchain wallet activity for the year, including total transactions, DeFi persona archetype, vibe statistics, and top decentralised applications used.",
  creator: {
    "@type": "WebApplication",
    name: "Stellar Wrap",
    url: "https://stellarwrap.vercel.app",
  },
  about: {
    "@type": "Thing",
    name: "Stellar blockchain activity",
    description:
      "On-chain transaction history, DeFi interactions, and wallet statistics on the Stellar network.",
  },
  inLanguage: "en",
  isAccessibleForFree: true,
  license: "https://creativecommons.org/licenses/by/4.0/",
};

export default function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <JsonLd data={sharePageJsonLd} />
      {children}
    </>
  );
}
